language: node_js

node_js:
  - "8.9.0"
  - "10.13.0"

script:
  # Run test script and generate coverage
  - npm run coverage
  # Run linting
  - npm run lint  
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.12.0
    coveralls < ./coverage/lcov.info
